package br.com.fiap.techchallenger4.logisticaentrega.dominio.entities.geo;

public enum TipoEnderecoEnum {
    AREA("Área"),
    ACESSO("Acesso"),
    ACAMPAMENTO("Acampamento"),
    ACESSO_LOCAL("Acesso Local"),
    ADRO("Adro"),
    AREA_ESPECIAL("Área Especial"),
    AEROPORTO("Aeroporto"),
    ALAMEDA("Alameda"),
    AVENIDA_MARGINAL_DIREITA("Avenida Marginal Direita"),
    AVENIDA_MARGINAL_ESQUERDA("Avenida Marginal Esquerda"),
    ANEL_VIARIO("Anel Viário"),
    ANTIGA_ESTRADA("Antiga Estrada"),
    ARTERIA("Artéria"),
    ALTO("Alto"),
    ATALHO("Atalho"),
    AREA_VERDE("Área Verde"),
    AVENIDA("Avenida"),
    AVENIDA_CONTORNO("Avenida Contorno"),
    AVENIDA_MARGINAL("Avenida Marginal"),
    AVENIDA_VELHA("Avenida Velha"),
    BALNEARIO("Balneário"),
    BECO("Beco"),
    BURACO("Buraco"),
    BELVEDERE("Belvedere"),
    BLOCO("Bloco"),
    BALAO("Balão"),
    BLOCOS("Blocos"),
    BULEVAR("Bulevar"),
    BOSQUE("Bosque"),
    BOULEVARD("Boulevard"),
    BAIXA("Baixa"),
    CAIS("Cais"),
    CALCADA("Calçada"),
    CAMINHO("Caminho"),
    CANAL("Canal"),
    CHACARA("Chácara"),
    CHAPADAO("Chapadão"),
    CICLOVIA("Ciclovia"),
    CIRCULAR("Circular"),
    CONJUNTO("Conjunto"),
    CONJUNTO_MUTIRAO("Conjunto Mutirão"),
    COMPLEXO_VIARIO("Complexo Viário"),
    COLONIA("Colônia"),
    COMUNIDADE("Comunidade"),
    CONDOMINIO("Condomínio"),
    CORREDOR("Corredor"),
    CAMPO("Campo"),
    CORREGO("Córrego"),
    CONTORNO("Contorno"),
    DESCIDA("Descida"),
    DESVIO("Desvio"),
    DISTRITO("Distrito"),
    ENTRE_BLOCO("Entre Bloco"),
    ESTRADA_INTERMUNICIPAL("Estrada Intermunicipal"),
    ENSEADA("Enseada"),
    ENTRADA_PARTICULAR("Entrada Particular"),
    ENTRE_QUADRA("Entre Quadra"),
    ESCADA("Escada"),
    ESCADARIA("Escadaria"),
    ESTRADA_ESTADUAL("Estrada Estadual"),
    ESTRADA_VICINAL("Estrada Vicinal"),
    ESTRADA_DE_LIGACAO("Estrada de Ligação"),
    ESTRADA_MUNICIPAL("Estrada Municipal"),
    ESPLANADA("Esplanada"),
    ESTRADA_DE_SERVIDAO("Estrada de Servidão"),
    ESTRADA("Estrada"),
    ESTRADA_VELHA("Estrada Velha"),
    ESTRADA_ANTIGA("Estrada Antiga"),
    ESTACAO("Estação"),
    ESTADIO("Estádio"),
    ESTANCIA("Estância"),
    ESTRADA_PARTICULAR("Estrada Particular"),
    ESTACIONAMENTO("Estacionamento"),
    EVANGELICA("Evangélica"),
    ELEVADA("Elevada"),
    EIXO_INDUSTRIAL("Eixo Industrial"),
    FAVELA("Favela"),
    FAZENDA("Fazenda"),
    FERROVIA("Ferrovia"),
    FONTE("Fonte"),
    FEIRA("Feira"),
    FORTE("Forte"),
    GALERIA("Galeria"),
    GRANJA("Granja"),
    NUCLEO_HABITACIONAL("Núcleo Habitacional"),
    ILHA("Ilha"),
    INDETERMINADO("Indeterminado"),
    ILHOTA("Ilhota"),
    JARDIM("Jardim"),
    JARDINETE("Jardinete"),
    LADEIRA("Ladeira"),
    LAGOA("Lagoa"),
    LAGO("Lago"),
    LOTEAMENTO("Loteamento"),
    LARGO("Largo"),
    LOTE("Lote"),
    MERCADO("Mercado"),
    MARINA("Marina"),
    MODULO("Modulo"),
    PROJECAO("Projeção"),
    MORRO("Morro"),
    MONTE("Monte"),
    NUCLEO("Núcleo"),
    NUCLEO_RURAL("Núcleo Rural"),
    OUTEIRO("Outeiro"),
    PARALELA("Paralela"),
    PASSEIO("Passeio"),
    PATIO("Pátio"),
    PRACA("Praça"),
    PRACA_DE_ESPORTES("Praça de Esportes"),
    PARADA("Parada"),
    PARADOURO("Paradouro"),
    PONTA("Ponta"),
    PRAIA("Praia"),
    PROLONGAMENTO("Prolongamento"),
    PARQUE_MUNICIPAL("Parque Municipal"),
    PARQUE("Parque"),
    PARQUE_RESIDENCIAL("Parque Residencial"),
    PASSARELA("Passarela"),
    PASSAGEM("Passagem"),
    PASSAGEM_DE_PEDESTRE("Passagem de Pedestre"),
    PASSAGEM_SUBTERRANEA("Passagem Subterrânea"),
    PONTE("Ponte"),
    PORTO("Porto"),
    QUADRA("Quadra"),
    QUINTA("Quinta"),
    QUINTAS("Quintas"),
    RUA("Rua"),
    RUA_INTEGRACAO("Rua Integração"),
    RUA_DE_LIGACAO("Rua de Ligação"),
    RUA_PARTICULAR("Rua Particular"),
    RUA_VELHA("Rua Velha"),
    RAMAL("Ramal"),
    RECREIO("Recreio"),
    RECANTO("Recanto"),
    RETIRO("Retiro"),
    RESIDENCIAL("Residencial"),
    RETA("Reta"),
    RUELA("Ruela"),
    RAMPA("Rampa"),
    RODO_ANEL("Rodo Anel"),
    RODOVIA("Rodovia"),
    ROTULA("Rotula"),
    RUA_DE_PEDESTRE("Rua de Pedestre"),
    MARGEM("Margem"),
    RETORNO("Retorno"),
    ROTATORIA("Rotatória"),
    SEGUNDA_AVENIDA("Segunda Avenida"),
    SITIO("Sitio"),
    SERVIDAO("Servidão"),
    SETOR("Setor"),
    SUBIDA("Subida"),
    TRINCHEIRA("Trincheira"),
    TERMINAL("Terminal"),
    TRECHO("Trecho"),
    TREVO("Trevo"),
    TUNEL("Túnel"),
    TRAVESSA("Travessa"),
    TRAVESSA_PARTICULAR("Travessa Particular"),
    TRAVESSA_VELHA("Travessa Velha"),
    UNIDADE("Unidade"),
    VIA("Via"),
    VIA_COLETORA("Via Coletora"),
    VIA_LOCAL("Via Local"),
    VIA_DE_ACESSO("Via de Acesso"),
    VALA("Vala"),
    VIA_COSTEIRA("Via Costeira"),
    VIADUTO("Viaduto"),
    VIA_EXPRESSA("Via Expressa"),
    VEREDA("Vereda"),
    VIA_ELEVADO("Via Elevado"),
    VILA("Vila"),
    VIELA("Viela"),
    VALE("Vale"),
    VIA_LITORANEA("Via Litorânea"),
    VIA_DE_PEDESTRE("Via de Pedestre"),
    VARIANTE("Variante"),
    ZIGUE_ZAGUE("Zigue-Zague");

    private final String descricao;

    TipoEnderecoEnum(String descricao) {
        this.descricao = descricao;
    }

    public String getDescricao() {
        return descricao;
    }
}

